### ISSUE TITLE
Remove item locks?

### ISSUE THREAD

**Issue by timwoj** [timwoj/shadowcraft-ui-python#42]
We added item locking back in Mists because of reforging. Now that we're two expansions on without reforging, does it make sense to keep that feature anymore?

**Comment by confusingbits** [comment]
When they removed the hit/expertise caps, they removed the noob trap and left only relatively minor optimization that would be available through reforging. I doubt we will see it's return. I certainly haven't heard any inclination towards bring it back from the devs because of the tedium it adds to gameplay.

We have the new talent system instead to fill that optimization niche.

**Comment by timwoj** [comment]
Fixed in https://github.com/ShadowCraft/shadowcraft-ui-react/commit/a6c3c0e89a635ee9a0322a2e27b8989e7942fd46
