### ISSUE TITLE
Outlaw warning left behind

### ISSUE THREAD

**Issue by timwoj** [timwoj/shadowcraft-ui-python#79]
Due to outlaw being 💩 , we drop a warning that says "Outlaw model not supported, at the moment." whenever a user picks outlaw. Unfortunately, we don't remove that warning when they see the light and switch away from outlaw.

**Comment by confusingbits** [comment]
OK, so I can clear warnings on spec swap, but that will just clear the combat spec warning for the combat spec itself. Along with the other specs.

I think this should be put into the back burner until the warning pane is refactored into a function of character state instead of the current 'message endpoint' it is right now.

I don't consider this of high priority right now.

**Comment by timwoj** [comment]
This was fixed with the warning changes, namely https://github.com/ShadowCraft/shadowcraft-ui-react/commit/df5d06620a95eecb84c27eb1238e7efe4b189e8f
