### ISSUE TITLE
adding an empty socket increases dps

### ISSUE THREAD

**Issue by confusingbits** [timwoj/shadowcraft-ui-python#81]
boggle

**Comment by timwoj** [comment]
I got a DPS decrease, but here's why:

![capture](https://user-images.githubusercontent.com/2653616/31867511-ed0889c2-b745-11e7-88df-976f376306bb.PNG)

**Comment by timwoj** [comment]
This is because bonus IDs are fucking stupid.

I have a 930 ilvl t20 cloak right now which is a normal cloak (900 base) titanforged to 930. It has a bonus ID of 1512 on it, which equates to a 40 ilvl increase. When the bonus ID popup appears, it sees that 1512 bonus ID, sets the ilvl selection to +40 and things break from there. We end up sending back a 940 item level in the action data and that makes the DPS go up because the stats change.

**Comment by timwoj** [comment]
That said, I really have no idea what to do about this one.

**Comment by confusingbits** [comment]
leaving this here so I remember:

There appear to be a few related problems.
The bonuses don't appear to be changed for the item after changing the titanforge
And the initial bonus selects appears to be 10 ilvl above the actual ilvl
And apparently equippeditem doesn't re render its tool tip link to reflect the updated ilvl....which may be related to the bonus 'missing' problem

**Comment by timwoj** [comment]
The variant stuff doesn't appear to fix this problem.
